# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: '1.8'

      - uses: actions/checkout@v2
      
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle
          key: v1-dependencies-${{ runner.os }}-${{ hashFiles('./build.gradle') }}

      # Runs a single command using the runners shell
      - name: download dependencies
        run: ./gradlew dependencies

      # Runs a set of commands using the runners shell
      - name: check and build
        run: ./gradlew check jar --max-workers=2

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: my-artifact
          path: |
            buildGradle/reports
            buildGradle/test-results
            buildGradle/libs
